version: "3"
services:
  server:
    build: ./server/
    command: npm start
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    ports:
      - "4000:4000"
    links:
      - mongo
    environment:
      PORT: 4000
      HOST: "0.0.0.0"
      DATABASE_URL: "mongodb://mongo/node-chat"
  client:
    build: ./client/
    command: npm start
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    links:
      - server
    environment:
      REACT_APP_BACKEND: server:4000
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
